@startuml "Visual layer"
abstract Node
abstract Attribute
abstract ConnectorType
abstract Recepticle
class GraphEditor
class Trigger
class Action
class Effect
class RGBDevice
class Connection
class NodeSource
class NodeTarget
class NumberAttribute
class TriggerConnector
class ActionConnector
class EffectConnector
SVGCompositor -- Node
GraphEditor o-- Node
GraphEditor o-- Connection
GraphEditor o-- SVGCompositor
Node o-- Attribute
Node <|-- Trigger
Node <|-- Action
Node <|-- Effect
Node <|-- RGBDevice
Connection -- Recepticle
Recepticle o- ConnectorType
Recepticle <|-- NodeTarget
Recepticle <|-- NodeSource
ConnectorType <|-- TriggerConnector
ConnectorType <|-- ActionConnector
ConnectorType <|-- EffectConnector
Attribute <|-- NumberAttribute
Attribute <|-- NodeSource
Attribute <|-- NodeTarget
@enduml