all: dist/index.html

dist/index.html: src/App.vue \
src/assets/VKTranslations.Nordic.csv \
src/components/ColorPickerAttribute.vue \
src/components/CustomToolbar.vue \
src/components/CustomToolbarButton.vue \
src/components/GraphEditor.vue \
src/components/KeyCodePicker.vue \
src/components/KeyCodePickerAttribute.vue \
src/graph/Interfaces/ColorPickerInterface.ts \
src/graph/Interfaces/KeyCodePickerInterface.ts \
src/graph/nodes/ActionNode.ts \
src/graph/nodes/CustomNodeTypes.ts \
src/graph/nodes/NodeGenerator.ts \
src/graph/nodes/TestNode.ts \
src/graph/RGBLightRunnerCommands.ts \
src/InjectionKeys.ts \
src/main.ts \
src/router/index.ts \
src/stores/counter.ts \
src/util/CSEvent.ts \
src/util/CsvReader.ts \
src/util/JSONRPC.ts \
src/util/RGBStudioAPI.ts \
src/util/RGBStudioMockAPI.ts \
src/util/WebViewConnection.ts \
src/views/EditorView.vue \
src/views/HomeView.vue
	npm run build
